/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author PC DOLPHIN
 */
public class CalculadoraUI extends javax.swing.JFrame {
    
    //public static javax.swing.JTextField txtpantalla;
    private boolean igual, inicio = true, operacion1, operacion2;
    private double a,b,c,memoria = 0, resultado, valor1, valor2;
    private String cadena, funcion, tipoOperaciones;
    //String memoria1;
    //String signo;
    //String memoria2;
        
    /**
     * Creates new form CalculadoraUI
     */
    public CalculadoraUI() {
        initComponents();
        txtpantalla.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param memoria1
     * @param memoria2
     * @param signo
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpantalla = new javax.swing.JTextField();
        BOTON_UNO = new javax.swing.JButton();
        BOTON_DOS = new javax.swing.JButton();
        BOTON_TRES = new javax.swing.JButton();
        BOTON_RESTA = new javax.swing.JButton();
        BOTON_C = new javax.swing.JButton();
        BOTON_CUATRO = new javax.swing.JButton();
        BOTON_CINCO = new javax.swing.JButton();
        BOTON_SEIS = new javax.swing.JButton();
        BOTON_SUMA = new javax.swing.JButton();
        BOTON_AC = new javax.swing.JButton();
        BOTON_SIETE = new javax.swing.JButton();
        BOTON_OCHO = new javax.swing.JButton();
        BOTON_NUEVE = new javax.swing.JButton();
        BOTON_MULTIPLICACION = new javax.swing.JButton();
        BOTON_INVERSO = new javax.swing.JButton();
        BOTON_CERO = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        BOTON_PUNTO = new javax.swing.JButton();
        BOTON_DIVISION = new javax.swing.JButton();
        BOTON_IGUAL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BOTON_Ms = new javax.swing.JButton();
        BOTON_MR = new javax.swing.JButton();
        BOTON_Mmas = new javax.swing.JButton();
        BOTON_Mmenos = new javax.swing.JButton();
        BOTON_Mc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        txtpantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtpantalla.setText("0");
        getContentPane().add(txtpantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 300, 33));

        BOTON_UNO.setBackground(new java.awt.Color(204, 204, 204));
        BOTON_UNO.setText("1");
        BOTON_UNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_UNOActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_UNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 52, 41));

        BOTON_DOS.setBackground(new java.awt.Color(204, 204, 204));
        BOTON_DOS.setText("2");
        BOTON_DOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_DOSActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_DOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 52, 41));

        BOTON_TRES.setBackground(new java.awt.Color(204, 204, 204));
        BOTON_TRES.setText("3");
        BOTON_TRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_TRESActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_TRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 52, 41));

        BOTON_RESTA.setBackground(new java.awt.Color(204, 204, 204));
        BOTON_RESTA.setText("-");
        BOTON_RESTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_RESTAActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_RESTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 52, 41));

        BOTON_C.setBackground(new java.awt.Color(255, 153, 0));
        BOTON_C.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_C.setText("C");
        BOTON_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_CActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 52, 41));

        BOTON_CUATRO.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_CUATRO.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_CUATRO.setText("4");
        BOTON_CUATRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_CUATROActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_CUATRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 52, 41));

        BOTON_CINCO.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_CINCO.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_CINCO.setText("5");
        BOTON_CINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_CINCOActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_CINCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 52, 41));

        BOTON_SEIS.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_SEIS.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_SEIS.setText("6");
        BOTON_SEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_SEISActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_SEIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 52, 41));

        BOTON_SUMA.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_SUMA.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_SUMA.setText("+");
        BOTON_SUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_SUMAActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_SUMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 52, 41));

        BOTON_AC.setBackground(new java.awt.Color(255, 153, 0));
        BOTON_AC.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_AC.setText("AC");
        BOTON_AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_ACActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 52, 41));

        BOTON_SIETE.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_SIETE.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_SIETE.setText("7");
        BOTON_SIETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_SIETEActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_SIETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 52, 41));

        BOTON_OCHO.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_OCHO.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_OCHO.setText("8");
        BOTON_OCHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_OCHOActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_OCHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 52, 41));

        BOTON_NUEVE.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_NUEVE.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_NUEVE.setText("9");
        BOTON_NUEVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_NUEVEActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_NUEVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 52, 41));

        BOTON_MULTIPLICACION.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_MULTIPLICACION.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_MULTIPLICACION.setText("*");
        BOTON_MULTIPLICACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_MULTIPLICACIONActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_MULTIPLICACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 52, 41));

        BOTON_INVERSO.setBackground(new java.awt.Color(255, 153, 0));
        BOTON_INVERSO.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_INVERSO.setText("1/x");
        BOTON_INVERSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_INVERSOActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_INVERSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 52, 41));

        BOTON_CERO.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_CERO.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_CERO.setText("0");
        BOTON_CERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_CEROActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_CERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 52, 41));

        jButton17.setBackground(new java.awt.Color(102, 102, 102));
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("+/-");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 52, 41));

        BOTON_PUNTO.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_PUNTO.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_PUNTO.setText(".");
        BOTON_PUNTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_PUNTOActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_PUNTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 52, 41));

        BOTON_DIVISION.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_DIVISION.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_DIVISION.setText("/");
        BOTON_DIVISION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_DIVISIONActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_DIVISION, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 52, 41));

        BOTON_IGUAL.setBackground(new java.awt.Color(255, 153, 0));
        BOTON_IGUAL.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_IGUAL.setText("=");
        BOTON_IGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_IGUALActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_IGUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 52, 41));

        jLabel1.setText("CALCULADORA v3.0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        BOTON_Ms.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_Ms.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_Ms.setText("Ms");
        BOTON_Ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_MsActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_Ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 52, 41));

        BOTON_MR.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_MR.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_MR.setText("MR");
        BOTON_MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_MRActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_MR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 52, 41));

        BOTON_Mmas.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_Mmas.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_Mmas.setText("M+");
        BOTON_Mmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_MmasActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_Mmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 52, 41));

        BOTON_Mmenos.setBackground(new java.awt.Color(102, 102, 102));
        BOTON_Mmenos.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_Mmenos.setText("M-");
        BOTON_Mmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_MmenosActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_Mmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 52, 41));

        BOTON_Mc.setBackground(new java.awt.Color(255, 153, 0));
        BOTON_Mc.setForeground(new java.awt.Color(255, 255, 255));
        BOTON_Mc.setText("MC");
        BOTON_Mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON_McActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON_Mc, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 52, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTON_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_CActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText("0");
        txtpantalla.setText("");
        inicio = true;
        funcion = "";
        operacion1 = true;
        operacion2 = true;
        igual = true;
        valor1 = 0;
        valor2 = 0;
        resultado = 0;
    }//GEN-LAST:event_BOTON_CActionPerformed

    private void BOTON_UNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_UNOActionPerformed
        // 1
        if (inicio == true) {
            txtpantalla.setText(" ");
            txtpantalla.setText("1");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"1");
        }
        
    }//GEN-LAST:event_BOTON_UNOActionPerformed

    private void BOTON_DOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_DOSActionPerformed
        // 2
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("2");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"2");
        }
    }//GEN-LAST:event_BOTON_DOSActionPerformed

    private void BOTON_TRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_TRESActionPerformed
        // 3
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("3");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"3");
        }
    }//GEN-LAST:event_BOTON_TRESActionPerformed

    private void BOTON_CUATROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_CUATROActionPerformed
        // 4
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("4");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"4");
        }
    }//GEN-LAST:event_BOTON_CUATROActionPerformed

    private void BOTON_CINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_CINCOActionPerformed
       // 5
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("5");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"5");
        }
    }//GEN-LAST:event_BOTON_CINCOActionPerformed

    private void BOTON_SEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_SEISActionPerformed
        // 6
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("6");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"6");
        }
    }//GEN-LAST:event_BOTON_SEISActionPerformed

    private void BOTON_SIETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_SIETEActionPerformed
        // 7
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("7");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"7");
        }
    }//GEN-LAST:event_BOTON_SIETEActionPerformed

    private void BOTON_OCHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_OCHOActionPerformed
       // 8
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("8");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"8");
        }
    }//GEN-LAST:event_BOTON_OCHOActionPerformed

    private void BOTON_NUEVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_NUEVEActionPerformed
       // 0
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("9");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"9");
        }
    }//GEN-LAST:event_BOTON_NUEVEActionPerformed

    private void BOTON_CEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_CEROActionPerformed
       // 0
        if (inicio == true) {
            txtpantalla.setText("");
            txtpantalla.setText("0");
            inicio = false;
        } else {
            txtpantalla.setText(txtpantalla.getText()+"0");
        }
    }//GEN-LAST:event_BOTON_CEROActionPerformed

    private void BOTON_PUNTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_PUNTOActionPerformed
        // PUNTO
        if (txtpantalla.getText().contains(".")){
        
    }else{
            txtpantalla.setText(txtpantalla.getText()+".");
            inicio = false;
        }
    }//GEN-LAST:event_BOTON_PUNTOActionPerformed

    private void BOTON_ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_ACActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText("0");
        txtpantalla.setText("");
        inicio = true;
        funcion = "";
    }//GEN-LAST:event_BOTON_ACActionPerformed

    private void BOTON_INVERSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_INVERSOActionPerformed
        // INVERSO
        valor1 = Double.parseDouble(txtpantalla.getText());
        txtpantalla.setText("reciproc( "+ valor1 +" )");
        txtpantalla.setText(1/valor1 +" ");
    }//GEN-LAST:event_BOTON_INVERSOActionPerformed

    private void BOTON_RESTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_RESTAActionPerformed
        // RESTA
       igual = true;
       inicio = true;
       
       if (operacion1 = true) {
           valor1 = Double.parseDouble(txtpantalla.getText());
           txtpantalla.setText("");
           txtpantalla.setText(txtpantalla.getText()+ "-");
           operacion1 = false;
       }else{
           if (operacion2 = true) {
           valor2 = Double.parseDouble(txtpantalla.getText());
           txtpantalla.setText(txtpantalla.getText()+ "-");
           operacion2 = false;
           }else{
                txtpantalla.setText(txtpantalla.getText()+ "-");
                Operaciones(resultado, valor2);
           }
       }
       tipoOperaciones = "-";
    }//GEN-LAST:event_BOTON_RESTAActionPerformed

    private void BOTON_SUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_SUMAActionPerformed
        // SUMA
       igual = true;
       inicio = true;
       
       if (operacion1 = true) {
           valor1 = Double.parseDouble(txtpantalla.getText());
           txtpantalla.setText("");
           txtpantalla.setText(txtpantalla.getText()+ "+");
           operacion1 = false;
       }else{
           if (operacion2 = true) {
           valor2 = Double.parseDouble(txtpantalla.getText());
           txtpantalla.setText(txtpantalla.getText()+ "+");
           operacion2 = false;
           }else{
                txtpantalla.setText(txtpantalla.getText()+ "+");
                Operaciones(resultado, valor2);
           }
       }
       tipoOperaciones = "+";
    }//GEN-LAST:event_BOTON_SUMAActionPerformed

    private void BOTON_MULTIPLICACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_MULTIPLICACIONActionPerformed
        // MULTIPLICACION
       igual = true;
       inicio = true;
       
       if (operacion1 = true) {
           valor1 = Double.parseDouble(txtpantalla.getText());
           txtpantalla.setText("");
           txtpantalla.setText(txtpantalla.getText()+ "*");
           operacion1 = false;
       }else{
           if (operacion2 = true) {
           valor2 = Double.parseDouble(txtpantalla.getText());
           txtpantalla.setText(txtpantalla.getText()+ "*");
           operacion2 = false;
           }else{
                txtpantalla.setText(txtpantalla.getText()+ "*");
                Operaciones(resultado, valor2);
           }
       }
       tipoOperaciones = "*";
    }//GEN-LAST:event_BOTON_MULTIPLICACIONActionPerformed

    private void BOTON_DIVISIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_DIVISIONActionPerformed
        // DIVISION
       igual = true;
       inicio = true;
       
       if (operacion1 = true) {
           valor1 = Double.parseDouble(txtpantalla.getText());
           txtpantalla.setText("");
           txtpantalla.setText(txtpantalla.getText()+ "/");
           operacion1 = false;
       }else{
           if (operacion2 = true) {
           valor2 = Double.parseDouble(txtpantalla.getText());
           txtpantalla.setText(txtpantalla.getText()+ "/");
           operacion2 = false;
           }else{
                txtpantalla.setText(txtpantalla.getText()+ "/");
                Operaciones(resultado, valor2);
           }
       }
       tipoOperaciones = "/";
    }//GEN-LAST:event_BOTON_DIVISIONActionPerformed

    private void Operaciones(double valor1, double valor2){
        switch(tipoOperaciones){
            //Case de la operacion suma
            case "+":
                resultado = valor1 + valor2;
                txtpantalla.setText(resultado + "");
                valor1 = Double.parseDouble(txtpantalla.getText());
                break;
                
            //Case de la operacion resta
            case "-":
                resultado = valor1 - valor2;
                txtpantalla.setText(resultado + "");
                valor1 = Double.parseDouble(txtpantalla.getText());
                break;
                
            //Case de la operacion suma
            case "*":
                resultado = valor1 * valor2;
                txtpantalla.setText(resultado + "");
                valor1 = Double.parseDouble(txtpantalla.getText());
                break;
                
            //Case de la operacion suma
            case "/":
                if (valor2 == 0){
                    txtpantalla.setText("Error");
                }else{
                    resultado = valor1 / valor2;
                    txtpantalla.setText(resultado + "");
                    valor1 = Double.parseDouble(txtpantalla.getText());
                    break;   
                }  
        }
    }
    
    private void BOTON_IGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_IGUALActionPerformed
        // IGUAL
        inicio = true;
        operacion1 = true;
        if (igual = true){
            if (tipoOperaciones == null){
                
            }else{
                valor2 = Double.parseDouble(txtpantalla.getText());
                txtpantalla.setText(txtpantalla.getText()+txtpantalla.getText());
                Operaciones(valor1, valor2);
                igual = false;
            }
        }else{
            txtpantalla.setText("");
            Operaciones(valor1, valor2);
        }
    }//GEN-LAST:event_BOTON_IGUALActionPerformed

    private void BOTON_MsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_MsActionPerformed
        // MS
        memoria = Double.parseDouble(txtpantalla.getText());
    }//GEN-LAST:event_BOTON_MsActionPerformed

    private void BOTON_MmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_MmasActionPerformed
        // M+
        memoria = memoria + Double.parseDouble(txtpantalla.getText());
    }//GEN-LAST:event_BOTON_MmasActionPerformed

    private void BOTON_MmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_MmenosActionPerformed
        // M-
        memoria = memoria - Double.parseDouble(txtpantalla.getText());
    }//GEN-LAST:event_BOTON_MmenosActionPerformed

    private void BOTON_McActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_McActionPerformed
        // MC
        memoria = 0;
    }//GEN-LAST:event_BOTON_McActionPerformed

    private void BOTON_MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON_MRActionPerformed
        // MR
        txtpantalla.setText(memoria + " ");
    }//GEN-LAST:event_BOTON_MRActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // CAMBIO DE SIGNO
        double nu1 = 0, nu2, nu3;
        nu2 = Double.parseDouble(txtpantalla.getText());
        nu3 = nu1 - nu2;
        txtpantalla.setText(nu3 + " ");
    }//GEN-LAST:event_jButton17ActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTON_AC;
    private javax.swing.JButton BOTON_C;
    private javax.swing.JButton BOTON_CERO;
    private javax.swing.JButton BOTON_CINCO;
    private javax.swing.JButton BOTON_CUATRO;
    private javax.swing.JButton BOTON_DIVISION;
    private javax.swing.JButton BOTON_DOS;
    private javax.swing.JButton BOTON_IGUAL;
    private javax.swing.JButton BOTON_INVERSO;
    private javax.swing.JButton BOTON_MR;
    private javax.swing.JButton BOTON_MULTIPLICACION;
    private javax.swing.JButton BOTON_Mc;
    private javax.swing.JButton BOTON_Mmas;
    private javax.swing.JButton BOTON_Mmenos;
    private javax.swing.JButton BOTON_Ms;
    private javax.swing.JButton BOTON_NUEVE;
    private javax.swing.JButton BOTON_OCHO;
    private javax.swing.JButton BOTON_PUNTO;
    private javax.swing.JButton BOTON_RESTA;
    private javax.swing.JButton BOTON_SEIS;
    private javax.swing.JButton BOTON_SIETE;
    private javax.swing.JButton BOTON_SUMA;
    private javax.swing.JButton BOTON_TRES;
    private javax.swing.JButton BOTON_UNO;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtpantalla;
    // End of variables declaration//GEN-END:variables
}
